version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      AUTH_URL: ${AUTH_IP}:${AUTH_PORT}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      GITHUB_ID: ${GITHUB_ID}
      GITHUB_SECRET: ${GITHUB_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    networks:
      - authentication-network
    restart: always

  authentication:
    container_name: authentication
    image: alazidis/e-commerce-auth
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    environment:
      AUTH_PORT: ${AUTH_PORT}
      AUTH_POSTGRES_USERNAME: ${AUTH_POSTGRES_USERNAME}
      AUTH_POSTGRES_PWD: ${AUTH_POSTGRES_PWD}
      AUTH_POSTGRES_IP: ${AUTH_POSTGRES_IP}
      AUTH_POSTGRES_PORT: ${AUTH_POSTGRES_PORT}
    networks:
      - authentication-network
    restart: always

  authentication_db:
    container_name: pg_container
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: ${AUTH_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PWD}
      POSTGRES_DB: USER
    ports:
      - "5432:5432"
    networks:
      - authentication-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - authentication-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:
  pgdata:

networks:
  authentication-network:
    driver: bridge
